### ISSUE TITLE
document quote command

### ISSUE THREAD

**Issue by JinnCirce** [bitbot-irc/bitbot#92]
`quote <category>` gives no hint to how it's used
also `qadd` might be best to allow per-channel limiting, so if people don't want them being quoted, it can be turned off on those channels, but not off globally (maybe setting it `"on"/"ops only"/"self only"/"off"` ? idk)

**Comment by jesopo** [comment]
I've got to make a decision about how I want quotes to work. do i only want quotes to be done by `!quotegrab` (that way the quote system can be trusted to be actual lines actually sent by a person holding that nickname) or do I allow people to manually add them with `!qadd`? quotes are per-network so having per-channel restrictions doesn't make much sense to me.

I also think the backend of the quote system could do with some TLC - I think it will become quite heavy on the server when one specific category has a LOT of quotes because it stores them in 1 JSON array in 1 row.
